FROM node:20-slim

# Установка pnpm
RUN npm install -g pnpm

WORKDIR /app

# Копирование package.json
COPY package.json pnpm-lock.yaml ./

# Установка зависимостей
RUN pnpm install --frozen-lockfile

# Копирование остальных файлов
COPY . ./

# Сборка для production с захардкоженным API URL
ENV NEXT_PUBLIC_API_URL=http://92.255.78.249:8003
RUN pnpm run build

EXPOSE 3000

# Production режим
CMD ["pnpm", "run", "start"]

